# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    srv_Paypal:
        class:        Services\Paypal
        arguments:     ["@doctrine.orm.entity_manager"]

    srv_TimeZone:
        class:        Services\TimeZone
        arguments:     ["@doctrine.orm.entity_manager", "%kernel.root_dir%"]
        
    srv_Loans:
        class:        Services\Loans
        arguments:     ["@doctrine.orm.entity_manager",  "@service_container"]    

    srv_Dashboard:
        class:        Services\Dashboard
        arguments:     ["@doctrine.orm.entity_manager",  "@service_container", "%kernel.root_dir%"] 

    app_bundle.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
            
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }        
       