app_homepage:
    path:   /backend
    defaults: { _controller: AppBundle:Payments:checkIn }


app_gallery:
        resource: "@AppBundle/Resources/config/routing/gallery.yml"
        prefix:   /backend/gallery

app_pricing:
        resource: "@AppBundle/Resources/config/routing/pricing.yml"
        prefix:   /backend/pricing


app_settings:
        resource: "@AppBundle/Resources/config/routing/settings.yml"
        prefix:   /backend/settings

app_setProfileImage:
        resource: "@AppBundle/Resources/config/routing/setProfileImage.yml"
        prefix:   /backend/setprofileimage

app_payments:
        resource: "@AppBundle/Resources/config/routing/payments.yml"
        prefix:   /backend/payments

app_client:
        resource: "@AppBundle/Resources/config/routing/client.yml"
        prefix:   /backend/client

app_loan:
        resource: "@AppBundle/Resources/config/routing/loan.yml"
        prefix:   /backend/loan 

app_loanpayment:
        resource: "@AppBundle/Resources/config/routing/loanpayment.yml"
        prefix:   /backend/loanpayment 

app_dashboard:
        resource: "@AppBundle/Resources/config/routing/dashboard.yml"
        prefix:   /backend/dashboard         

register:
        path: /register
        defaults: { _controller: "AppBundle:User:register" }
login:
        path: /login
        defaults: { _controller: "AppBundle:User:login" }

login_check:
        path: /login_check
logout:
        path: /logout

rememberPassword:
        path: /rememberPassword
        defaults: { _controller: "AppBundle:User:rememberPassword" }

user_profile_image:
    path:     /user/profileImage
    defaults: { _controller: "AppBundle:User:profileImage" }        



