AppBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        usr_email:
            columns:
                - usr_email
    id:
        usrId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: usr_id
            generator:
                strategy: IDENTITY
    fields:
        usrUsername:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: usr_username
        usrPassword:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
            column: usr_password
        usrEmail:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: usr_email
        usrRole:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: usr_role
        usrStatus:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: usr_status
        usrProfileImage:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: usr_profile_image
        usrTokenConfirmation:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: usr_token_confirmation
        usrForgotPassword:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: usr_forgot_password
        usrCreated:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: usr_created
        usrUpdated:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: usr_updated
        usrActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: usr_active
        usrLastLogin:
            type: datetime
            nullable: true
            column: usr_last_login
        usrNotificationContactForm:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: usr_notification_contact_form
        usrNotificationPayment:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: usr_notification_payment
        usrShow:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: usr_show
        usrDateFormat:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                default: mm/dd/yyyy
            column: usr_date_format
    lifecycleCallbacks: {  }
